# Generated by Django 3.2.5 on 2022-01-08 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('n_id', models.AutoField(primary_key=True, serialize=False)),
                ('notification', models.CharField(max_length=1000)),
                ('accident_date', models.DateTimeField(auto_now_add=True)),
                ('lattitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('accepted', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
