# Generated by Django 3.2.5 on 2022-01-08 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accidentdetectionapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('h_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('h_lattitude', models.FloatField(blank=True, null=True)),
                ('h_longitude', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
